### ISSUE TITLE
Bazel tutorial with examples

### ISSUE THREAD

**Issue by zpervan** [eliasdaler/imgui-sfml#134]
As Bazel is gaining more influence as a C++ build system, it would be helpful for developers (especially that are starting out) to have a basic how-to Bazelize imgui-SFML and develop your game/project with it.
Managed to make it work so I can help you out regarding this topic.

**Comment by eliasdaler** [comment]
Hello
Bazel is very far from being popular compared to CMake and Conan, so I don't think that a lot of people will use it. I think Meson is more popular in C++ sphere, but I don't want to include it as well, because I don't want to have another file I have to maintain for a build system I'm not using...

I'll be happy to include the link to Bazel script in the README.md, so send a link here once you have a repo/gist for it.

**Comment by zpervan** [comment]
Hi,
Here is the gist file which with instructions to bazelilze Imgui-SFML:
https://gist.github.com/zpervan/00faf923e770bce12a71b255c988cac7

Also, at the bottom is a template repository which contains all needed files to run your example code.

**Comment by eliasdaler** [comment]
Nice article! I'll link to it soon
By the way, there's no need to link with sfml-audio and sfml-network to use ImGui-SFML (most people might want to link with audio, but network is pretty big and unnecessary in most cases)

**Comment by zpervan** [comment]
Glad that you like it :) Yeah, you're right about linking the audio and network module. Will change that.

**Comment by eliasdaler** [comment]
Added to readme, closing for now.
