### ISSUE TITLE
Adding compatibility with ImGui conan package

### ISSUE THREAD

**Issue by SylEze** [eliasdaler/imgui-sfml#148]
Hello, I want to use both dependencies in my conanfile.txt: `imgui/1.79` and `imgui-sfml/2.1@bincrafters/stable`

`imgui-sfml` conan package has not yet the capacity to link with an `imgui` conan package.

The reason is that `imgui-sfml` is looking for an `IMGUI_DIR` with both `imgui.cpp` and `imgui.hpp` files but `imgui` conan package is already built and therefore it contains no `imgui.cpp`. Moreover it doesn't know anything about an `IMGUI_DIR` at all if it is not manually specified.

The workaround I'm currently using forced me to clone `imgui-sfml` in my repo and write that stuff:
```cmake
add_library(imgui-sfml 3rdParty/imgui-sfml/imgui-SFML.cpp)
target_include_directories(imgui-sfml PUBLIC 3rdParty/imgui-sfml)
target_link_libraries(imgui-sfml PUBLIC CONAN_PKG::sfml CONAN_PKG::imgui)
```

Thanks for reading.

**Comment by eliasdaler** [comment]
Hello
I think that this can be fixed by creating "IMGUI_SFML_FIND_IMGUI" flag and doing this in CMake, right?

```cmake
if (IMGUI_SFML_FIND_IMGUI)
    find_package(ImGui 1.68 REQUIRED)
endif()
```

This way, you'll still need to define `IMGUI_INCLUDE_DIR` and `IMGUI_SOURCES` (can set it to target's name) to properly link with ImGui.

The separate ImGui package kinda worries me, though. How does it work? I felt like ImGui doesn't really work as a separate library without building it and statically linking it with a backend implementation.

**Comment by SylEze** [comment]
Looking at [conan-center-index/imgui/CMakeLists.txt#l26](https://github.com/conan-io/conan-center-index/blob/master/recipes/imgui/all/CMakeLists.txt#L26), it seems that the ImGui package is building without any backend implementation.

May it cause any issue ?

**Comment by eliasdaler** [comment]
Yes. Right now ImGui-SFML is meant to be linked with ImGui statically, I don't think that it's possible to link it dynamically without problems

**Comment by SylEze** [comment]
For the moment I'm dynamically linking and it's working. If I got any issue I'll let you know.
