### ISSUE TITLE
Is there any possibility to scale up whole UI?

### ISSUE THREAD

**Issue by Patys** [eliasdaler/imgui-sfml#156]
How I can scale up all the GUI? Applying sf::View to window doesn't make any changes :/

**Comment by eliasdaler** [comment]
See this: https://github.com/ocornut/imgui/issues/436

Applying view to window doesn't change anything, because rendering function is not using Views for transforms - it'll be pretty resource intensive. And you also need to remember that if you scale the UI, ImGui needs to somehow now that all widgets now have differently sized collision boxes...

So, it's not ImGui-SFML issue - it's a Dear ImGui issue.
