### ISSUE TITLE
What GetCursorPos really does?

### ISSUE THREAD

**Issue by EfeOsman** [eliasdaler/imgui-sfml#161]
i was trying to apply my mouse positions to rendertexture surface that im drawing into ImGui tab bar 
and i found GetCursorPos and it worked but i dont know why because i thought GetCursorPos gonna give position of mouse relative to window 
my question: What GetCursorPos really does?
(im asking help here because i cant open issue to imgui repo (idk why?? i have never opened issue there))

**Comment by eliasdaler** [comment]
Don't open issues/questions about ImGui here. Go to [ImGui discussions page](https://github.com/ocornut/imgui/discussions) and open threads here. 
Your issues on ImGui get closed, because you're not following the template that you're asked to fill.

What you probably need is `GetCursorScreenPos` after all.
