### ISSUE TITLE
How to create and pass a font atlas to Init()?

### ISSUE THREAD

**Issue by DEAGS3000** [eliasdaler/imgui-sfml#23]
I want to use utf-8 characters in my program, and I noticed that parameter type is sf::Texture*. So how to create this "font atlas" and convert it to sf::Texture*? If I use sf::Font.getTexture, it will return a const one. 
Can you paste an example here? Thanks.

**Comment by DEAGS3000** [comment]
I did it like this: 
`
ImGui::SFML::Init(window);
ImGuiIO& io = ImGui::GetIO();
io.Fonts->ClearFonts();
io.Fonts->AddFontFromFileTTF("xarialuni.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesChinese());
sf::Texture *font_texture = new sf::Texture;
ImGui::SFML::createFontTexture(*font_texture);
ImGui::SFML::setFontTexture(*font_texture);
`

**Comment by MarkSill** [comment]
I recently had a lot of trouble with this. Here's what I did:

First, I created the SFML window as usual. I did NOT yet initialize imgui-sfml.

Next, I create the font _almost_ the same way as you. Instead of calling `io.Fonts->ClearFonts()`, I call `io.Fonts->AddFontDefault()`, which, as I understand it, is the way to do that. I also don't call `ImGui::SFML::createFontTexture()` or `ImGui::SFML::setFontTexture()`. You'll also need to save the `ImFont*` that's returned by `io.Fonts->AddFontFromFileTTF()`. You'll use that to set the font later.

Finally, call `ImGui::SFML::Init()` with your window, and no texture. This will create the font for you automatically. I don't think that's intentional on the part of the library, but it works well.

To use the font, I call `ImGui::PushFont()` and `ImGui::PopFont()`.

**Comment by eliasdaler** [comment]
[Font how-to!](https://github.com/eliasdaler/imgui-sfml#fonts-how-to)

**Comment by metaleap** [comment]
> _**Finally,**_ call `ImGui::SFML::Init()`

How do I do this? If I do Init **_after_** GetIO, it errors with:

> ImGui::GetIO(): Assertion `GImGui != __null && "No current context. Did you call ImGui::CreateContext() and ImGui::SetCurrentContext() ?"' failed.

The font how-to I initially followed to the letter, nonetheless it still failed to load every TTF I gave it, and I tried a handful. Always absolute paths, too, no location ambiguities at all.
